# Stage 1: Build the React application
FROM node:10.18.0

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY client/package*.json .

# Install dependencies
WORKDIR /usr/src/app
RUN npm install --production

# Copy the rest of your application code to the container
COPY . .

EXPOSE 8000
# Start the server
CMD ["npm", "start"]

