# Dockerfile for Nginx Proxy

FROM nginx:latest


# Copy SSL certificates
COPY ./ssl/localhost.crt /etc/ssl/certs/localhost.crt
COPY ./ssl/localhost.key /etc/ssl/private/localhost.key

# Copy custom Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 443 for HTTPS
EXPOSE 443
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

